import {
  AppUser,
  AuditLog,
  BlockedUserPair,
  Driver,
  FixedPassenger,
  Occurrence,
  PendingApproval,
  PlatformConfig,
  Ride,
  RideCategory,
  RideMediaRecord,
  SafePoint,
  StateOperation,
  ThirdPartyPassenger,
  TransportContract,
  OfficialRoadInterdiction,
  RouteDeviationRecord,
} from './types';

export const initialConfig: PlatformConfig = {
  name: 'W-DRIVER AMÉRICA LATINA BRASIL JOÃO PESSOA-PB',
  slogan: 'Quem escolhe preço corre riscos. Quem escolhe a W-DRIVER escolhe chegar bem!',
  commissionRate: 10, // 10% Central
  driverRate: 90, // 90% Motorista
  primaryColor: '#83d600',
  dailyGoal: 47,
  shift1Start: '09:00',
  shift1End: '10:30',
  shift2Start: '12:00',
  shift2End: '18:30',
  dynamicEnabled: true,
  maxDynamicMultiplier: 2.0,
  currentDynamicMultiplier: 1.0,
  peakHours: [
    { period: '04:00 – 09:00', label: 'Pico Manhã (Abertura comercial / saúde)', baseMultiplier: 1.15, active: true },
    { period: '11:30 – 15:00', label: 'Pico Almoço (Empresas e gastronomia)', baseMultiplier: 1.10, active: true },
    { period: '16:30 – 20:00', label: 'Pico Tarde / Noite (Saída do trabalho)', baseMultiplier: 1.25, active: true },
    { period: '22:00 – 04:00', label: 'Pico Noturno / Baladas / Litoral', baseMultiplier: 1.30, active: true },
  ],
  categoriesRules: {
    'W-BIKE': {
      id: 'W-BIKE',
      name: 'W-BIKE',
      icon: '🚲',
      description: 'Até 4 km: R$ 6,00 | Acima de 4 km: R$ 0,90/km',
      fixedFareUnder4km: 6.0,
      ratePerKmAbove4km: 0.9,
      contractRatePerKm: 0.9,
      active: true,
    },
    'W-MOTO COMUM': {
      id: 'W-MOTO COMUM',
      name: 'W-MOTO COMUM',
      icon: '🏍️',
      description: 'Até 4 km: R$ 6,00 | Acima de 4 km: R$ 1,00/km',
      fixedFareUnder4km: 6.0,
      ratePerKmAbove4km: 1.0,
      contractRatePerKm: 1.0,
      active: true,
    },
    'W-MOTO PRIME': {
      id: 'W-MOTO PRIME',
      name: 'W-MOTO PRIME',
      icon: '🏍️',
      description: 'Até 4 km: R$ 6,00 | Acima de 4 km: R$ 1,30/km',
      fixedFareUnder4km: 6.0,
      ratePerKmAbove4km: 1.3,
      contractRatePerKm: 1.3,
      active: true,
    },
    'W-CARRO COMUM': {
      id: 'W-CARRO COMUM',
      name: 'W-CARRO COMUM',
      icon: '🚗',
      description: 'Até 4 km: R$ 8,00 | Acima de 4 km: R$ 1,75/km',
      fixedFareUnder4km: 8.0,
      ratePerKmAbove4km: 1.75,
      contractRatePerKm: 1.75,
      active: true,
    },
    'W-CARRO PRIME': {
      id: 'W-CARRO PRIME',
      name: 'W-CARRO PRIME',
      icon: '🚙',
      description: 'Até 4 km: R$ 8,00 | Acima de 4 km: R$ 2,00/km',
      fixedFareUnder4km: 8.0,
      ratePerKmAbove4km: 2.0,
      contractRatePerKm: 2.0,
      active: true,
    },
    'W-EXECUTIVO': {
      id: 'W-EXECUTIVO',
      name: 'W-EXECUTIVO',
      icon: '🚘',
      description: 'Até 4 km: R$ 10,00 | Acima de 4 km: R$ 3,00/km',
      fixedFareUnder4km: 10.0,
      ratePerKmAbove4km: 3.0,
      contractRatePerKm: 3.0,
      active: true,
    },
    'W-EXECUTIVO PRIME': {
      id: 'W-EXECUTIVO PRIME',
      name: 'W-EXECUTIVO PRIME',
      icon: '🚘',
      description: 'Até 4 km: R$ 10,00 | Acima de 4 km: R$ 3,50/km',
      fixedFareUnder4km: 10.0,
      ratePerKmAbove4km: 3.5,
      contractRatePerKm: 3.5,
      active: true,
    },
    'W-LUXO': {
      id: 'W-LUXO',
      name: 'W-LUXO',
      icon: '👑',
      description: 'Serviço exclusivo por contrato corporativo / blindado',
      fixedFareUnder4km: 25.0,
      ratePerKmAbove4km: 4.5,
      contractRatePerKm: 4.5,
      active: true,
      isContractOnly: true,
    },
    'W-TÁXI': {
      id: 'W-TÁXI',
      name: 'W-TÁXI',
      icon: '🚕',
      description: 'Faixa exclusiva em corredores. Regulamentação oficial',
      fixedFareUnder4km: 8.0,
      ratePerKmAbove4km: 3.2,
      contractRatePerKm: 3.0,
      active: true,
    },
    'W-DELIVERY': {
      id: 'W-DELIVERY',
      name: 'W-DELIVERY',
      icon: '📦',
      description: 'Entregas corporativas e documentos. Até 3 km R$ 7,00',
      fixedFareUnder4km: 7.0,
      ratePerKmAbove4km: 1.2,
      contractRatePerKm: 1.2,
      active: true,
    },
    // Aliases retrocompatíveis
    'W-MOTO': {
      id: 'W-MOTO',
      name: 'W-MOTO',
      icon: '🏍️',
      description: 'Até 4 km: R$ 6,00 | Acima de 4 km: R$ 1,00/km',
      fixedFareUnder4km: 6.0,
      ratePerKmAbove4km: 1.0,
      contractRatePerKm: 1.0,
      active: true,
    },
    'W-CARRO': {
      id: 'W-CARRO',
      name: 'W-CARRO',
      icon: '🚗',
      description: 'Até 4 km: R$ 8,00 | Acima de 4 km: R$ 1,75/km',
      fixedFareUnder4km: 8.0,
      ratePerKmAbove4km: 1.75,
      contractRatePerKm: 1.75,
      active: true,
    },
    'W-EXECUTIVE': {
      id: 'W-EXECUTIVE',
      name: 'W-EXECUTIVE',
      icon: '🚘',
      description: 'Até 4 km: R$ 10,00 | Acima de 4 km: R$ 3,00/km',
      fixedFareUnder4km: 10.0,
      ratePerKmAbove4km: 3.0,
      contractRatePerKm: 3.0,
      active: true,
    },
  },
  baseFare: {
    'W-MOTO COMUM': { base: 6.0, perKm: 1.0, perMin: 0.0 },
    'W-MOTO PRIME': { base: 6.0, perKm: 1.3, perMin: 0.0 },
    'W-CARRO COMUM': { base: 8.0, perKm: 1.75, perMin: 0.0 },
    'W-CARRO PRIME': { base: 8.0, perKm: 2.0, perMin: 0.0 },
    'W-EXECUTIVO': { base: 10.0, perKm: 3.0, perMin: 0.0 },
    'W-EXECUTIVO PRIME': { base: 10.0, perKm: 3.5, perMin: 0.0 },
    'W-LUXO': { base: 25.0, perKm: 4.5, perMin: 0.0 },
    'W-MOTO': { base: 6.0, perKm: 1.0, perMin: 0.0 },
    'W-CARRO': { base: 8.0, perKm: 1.75, perMin: 0.0 },
    'W-BIKE': { base: 6.0, perKm: 0.9, perMin: 0.0 },
    'W-TÁXI': { base: 8.0, perKm: 3.2, perMin: 0.0 },
    'W-DELIVERY': { base: 7.0, perKm: 1.2, perMin: 0.0 },
    'W-EXECUTIVE': { base: 10.0, perKm: 3.0, perMin: 0.0 },
  },
};

/**
 * FONTE ÚNICA DE VERDADE: CÁLCULO OFICIAL DE TARIFAS W-DRIVER
 * Regra:
 * - Até 4 km: valor fixo/mínimo da categoria.
 * - Acima de 4 km: quilometragem TOTAL multiplicada pelo valor do km da categoria.
 *   (NÃO cobrar apenas os excedentes! Ex: 5 km em W-CARRO COMUM = 5 * 1.75 = R$ 8.75).
 * - CONTRATOS: Preço fixo por km durante toda a vigência, SEM DINÂMICA.
 */
export function calculateRidePrice(
  category: RideCategory,
  distanceKm: number,
  config: PlatformConfig,
  isContract = false
): {
  price: number;
  ruleExplanation: string;
  commissionCentral: number;
  driverEarnings: number;
  isContract: boolean;
} {
  let normCat = category;
  if (category === 'W-MOTO') normCat = 'W-MOTO COMUM';
  else if (category === 'W-CARRO') normCat = 'W-CARRO COMUM';
  else if (category === 'W-EXECUTIVE') normCat = 'W-EXECUTIVO';

  const rule = config.categoriesRules[normCat] || config.categoriesRules['W-CARRO COMUM'];

  if (isContract) {
    // REGRA ABSOLUTA DE CONTRATO: PREÇO FIXO SEM DINÂMICA
    const price = Math.round(distanceKm * rule.contractRatePerKm * 100) / 100;
    const commission = Math.round(price * (config.commissionRate / 100) * 100) / 100;
    return {
      price,
      ruleExplanation: `Contrato Pré-Pago: R$ ${rule.contractRatePerKm.toFixed(2)}/km fixo (sem dinâmica)`,
      commissionCentral: commission,
      driverEarnings: Math.round((price - commission) * 100) / 100,
      isContract: true,
    };
  }

  // Viagem avulsa
  let basePrice = 0;
  let explanation = '';

  if (distanceKm <= 4) {
    basePrice = rule.fixedFareUnder4km;
    explanation = `Até 4 km: R$ ${rule.fixedFareUnder4km.toFixed(2)} (tarifa mínima)`;
  } else {
    basePrice = Math.round(distanceKm * rule.ratePerKmAbove4km * 100) / 100;
    explanation = `Acima de 4 km: ${distanceKm.toFixed(1)} km total × R$ ${rule.ratePerKmAbove4km.toFixed(2)}/km = R$ ${basePrice.toFixed(2)}`;
  }

  const multiplier = config.dynamicEnabled ? Math.min(config.maxDynamicMultiplier, config.currentDynamicMultiplier || 1.0) : 1.0;
  const finalPrice = Math.round(basePrice * multiplier * 100) / 100;

  if (multiplier > 1.0) {
    explanation += ` [Dinâmica ${multiplier.toFixed(1)}x = R$ ${finalPrice.toFixed(2)}]`;
  }

  const commission = Math.round(finalPrice * (config.commissionRate / 100) * 100) / 100;

  return {
    price: finalPrice,
    ruleExplanation: explanation,
    commissionCentral: commission,
    driverEarnings: Math.round((finalPrice - commission) * 100) / 100,
    isContract: false,
  };
}

export const initialDrivers: Driver[] = [
  {
    id: 'drv-1',
    userCode: 'W-0701',
    name: 'Diego Wallace (Proprietário Autorizado)',
    vehicle: 'Honda CG 160 Titan',
    plate: 'QFA-8921',
    category: 'W-MOTO COMUM',
    activeCategory: 'W-MOTO COMUM',
    isOwnerAdmin: true,
    enabledCategories: [
      'W-BIKE',
      'W-MOTO COMUM',
      'W-MOTO PRIME',
      'W-CARRO COMUM',
      'W-CARRO PRIME',
      'W-EXECUTIVO',
      'W-TÁXI',
      'W-LUXO',
    ],
    vehicleByCategory: {
      'W-BIKE': { vehicle: 'Caloi E-Vibe Elite E-Bike', plate: 'W-BIKE-PB' },
      'W-MOTO COMUM': { vehicle: 'Honda CG 160 Titan', plate: 'QFA-8921' },
      'W-MOTO PRIME': { vehicle: 'Yamaha FZ25 Fazer Prime', plate: 'QFB-1102' },
      'W-CARRO COMUM': { vehicle: 'Chevrolet Onix Plus LTZ', plate: 'QFL-4412' },
      'W-CARRO PRIME': { vehicle: 'Jeep Compass Longitude Turbo', plate: 'QFR-9900' },
      'W-EXECUTIVO': { vehicle: 'Toyota Corolla Altis Hybrid VIP', plate: 'RJA-7H33' },
      'W-TÁXI': { vehicle: 'Fiat Cronos Drive Táxi Oficial', plate: 'PB-TX-0701' },
      'W-LUXO': { vehicle: 'BMW 320i M Sport Blindado', plate: 'RPB-0701' },
    },
    rating: 5.0,
    status: 'online',
    lat: -7.0985,
    lng: -34.8362,
    state: 'PB',
    city: 'João Pessoa',
    neighborhood: 'Manaíra',
    completedRidesToday: 24,
    phone: '(83) 98841-2099',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    habilitado: true,
    orientacaoConcluida: true,
    refusalCount: 0,
    cooldownUntil: null,
  },
  {
    id: 'drv-2',
    userCode: 'W-0702',
    name: 'Carlos Eduardo Silva',
    vehicle: 'Chevrolet Onix Plus',
    plate: 'QFL-4412',
    category: 'W-CARRO COMUM',
    rating: 4.95,
    status: 'em_corrida',
    lat: -7.1145,
    lng: -34.8285,
    state: 'PB',
    city: 'João Pessoa',
    neighborhood: 'Tambaú',
    completedRidesToday: 18,
    phone: '(83) 98712-4433',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    habilitado: true,
    orientacaoConcluida: true,
  },
  {
    id: 'drv-3',
    userCode: 'W-0703',
    name: 'Lucas Martins Oliveira',
    vehicle: 'Fiat Mobi Like',
    plate: 'QFP-9820',
    category: 'W-CARRO COMUM',
    rating: 4.91,
    status: 'online',
    lat: -7.0722,
    lng: -34.8458,
    state: 'PB',
    city: 'João Pessoa',
    neighborhood: 'Bessa',
    completedRidesToday: 15,
    phone: '(83) 99120-7761',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    habilitado: true,
    orientacaoConcluida: true,
  },
  {
    id: 'drv-4',
    userCode: 'W-0704',
    name: 'Mariana Duarte Souza',
    vehicle: 'Yamaha Fazer 250',
    plate: 'QFR-1123',
    category: 'W-MOTO PRIME',
    rating: 4.97,
    status: 'online',
    lat: -7.1298,
    lng: -34.8234,
    state: 'PB',
    city: 'João Pessoa',
    neighborhood: 'Cabo Branco',
    completedRidesToday: 21,
    phone: '(83) 98833-9002',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    habilitado: true,
    orientacaoConcluida: true,
  },
  {
    id: 'drv-5',
    userCode: 'W-0705',
    name: 'Roberto Cavalcanti',
    vehicle: 'Toyota Corolla Hybrid',
    plate: 'RJA-7H33',
    category: 'W-EXECUTIVO',
    rating: 5.0,
    status: 'online',
    lat: -7.1355,
    lng: -34.8152,
    state: 'PB',
    city: 'João Pessoa',
    neighborhood: 'Altiplano',
    completedRidesToday: 11,
    phone: '(83) 99314-1188',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    habilitado: true,
    orientacaoConcluida: true,
  },
  {
    id: 'drv-6',
    userCode: 'W-0706',
    name: 'Thiago Farias',
    vehicle: 'Caloi Strada Pro E-Bike',
    plate: 'WBK-049',
    category: 'W-BIKE',
    rating: 4.88,
    status: 'online',
    lat: -7.1192,
    lng: -34.8315,
    state: 'PB',
    city: 'João Pessoa',
    neighborhood: 'Tambaú / Orla',
    completedRidesToday: 12,
    phone: '(83) 98655-2244',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    habilitado: true,
    orientacaoConcluida: true,
  },
  {
    id: 'drv-7',
    userCode: 'W-0707',
    name: 'José Augusto Ferreira',
    vehicle: 'Spin Premier 7 Lugares',
    plate: 'QFV-5509',
    category: 'W-CARRO PRIME',
    rating: 4.96,
    status: 'online',
    lat: -7.1472,
    lng: -34.8234,
    state: 'PB',
    city: 'João Pessoa',
    neighborhood: 'Miramar',
    completedRidesToday: 9,
    phone: '(83) 99401-3312',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    habilitado: true,
    orientacaoConcluida: true,
  },
];

export const initialFixedPassengers: FixedPassenger[] = [
  {
    id: 'fix-1',
    userCode: 'W-0701',
    name: 'Ana Cláudia (Comércio Torre)',
    phone: '(83) 98822-1011',
    pickupTime: '09:00',
    shift: 'manha',
    origin: 'Bessa (Praia)',
    destination: 'Torre / Clínicas Epitácio',
    dailyValue: 14.5,
    monthlyValue: 319.0,
    status: 'ativo',
    frequency: 'Segunda a Sexta (Rotina)',
    notes: 'Cliente pontual, aguardar na portaria do Residencial Atlantis.',
  },
  {
    id: 'fix-2',
    userCode: 'W-0702',
    name: 'Dr. Marcos Albuquerque',
    phone: '(83) 99144-8822',
    pickupTime: '12:15',
    shift: 'almoco',
    origin: 'Centro Médico Tambaú',
    destination: 'Manaíra Shopping (Praça Gourmet)',
    dailyValue: 12.0,
    monthlyValue: 264.0,
    status: 'ativo',
    frequency: 'Segunda a Sexta',
    notes: 'Prefere W-Carro climatizado com som ambiente.',
  },
  {
    id: 'fix-3',
    userCode: 'W-0703',
    name: 'Camila & Sofia (Escola Maple Bear)',
    phone: '(83) 98711-4545',
    pickupTime: '12:30',
    shift: 'almoco',
    origin: 'Altiplano Nobre',
    destination: 'Escola Internacional Miramar',
    dailyValue: 18.0,
    monthlyValue: 396.0,
    status: 'ativo',
    frequency: 'Segunda a Sexta',
    notes: 'Transporte escolar privativo VIP.',
  },
  {
    id: 'fix-4',
    userCode: 'W-0704',
    name: 'Juliana Barbosa (Tribunal de Justiça)',
    phone: '(83) 99655-0909',
    pickupTime: '17:30',
    shift: 'tarde',
    origin: 'Centro Cívico (Praça dos Três Poderes)',
    destination: 'Cabo Branco (Av. Beira Rio)',
    dailyValue: 22.0,
    monthlyValue: 484.0,
    status: 'ativo',
    frequency: 'Segunda a Quinta',
    notes: 'Saída às 17h30 exatas em ponto.',
  },
  {
    id: 'fix-5',
    userCode: 'W-0705',
    name: 'Lucas Vilar (Escritório de Advocacia)',
    phone: '(83) 98877-3344',
    pickupTime: '18:15',
    shift: 'tarde',
    origin: 'Edifício Epitácio Pessoa',
    destination: 'Bessa (Av. Governador Argemiro)',
    dailyValue: 19.5,
    monthlyValue: 429.0,
    status: 'ativo',
    frequency: 'Segunda a Sexta',
    notes: 'Pagamento mensal direto via Pix no dia 05.',
  },
];

export const initialPendingApprovals: PendingApproval[] = [
  {
    id: 'app-1',
    userCode: 'W-0708',
    name: 'Carlos Eduardo Silva',
    type: 'motorista',
    state: 'PB',
    city: 'João Pessoa',
    registerDate: 'Hoje, 10:32',
    docsSent: 6,
    docsTotal: 6,
    status: 'pendente',
    vehicleInfo: 'Chevrolet Onix Plus 2023 - QFL-4412',
    category: 'W-CARRO COMUM',
    phone: '(83) 98712-4433',
    cpf: '042.***.***-81',
    documents: [
      { id: 'd1', name: 'CNH com EAR (Exerce Atividade Remunerada)', type: 'PDF', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd2', name: 'CRLV Digital 2025/2026', type: 'PDF', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd3', name: 'Certidão Negativa de Antecedentes Criminais', type: 'PDF', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd4', name: 'Comprovante de Residência (João Pessoa)', type: 'Imagem', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd5', name: 'Foto do Veículo (Frente e Placa)', type: 'Imagem', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd6', name: 'Selfie com Documento', type: 'Imagem', status: 'pendente', dateUploaded: 'Hoje' },
    ],
  },
  {
    id: 'app-2',
    userCode: 'W-0709',
    name: 'Lucas Martins Oliveira',
    type: 'motorista',
    state: 'PB',
    city: 'João Pessoa',
    registerDate: 'Hoje, 09:15',
    docsSent: 6,
    docsTotal: 6,
    status: 'pendente',
    vehicleInfo: 'Fiat Mobi Like 2024 - QFP-9820',
    category: 'W-CARRO COMUM',
    phone: '(83) 99120-7761',
    cpf: '089.***.***-23',
    documents: [
      { id: 'd1', name: 'CNH Digital com EAR', type: 'PDF', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd2', name: 'CRLV Quitado', type: 'PDF', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd3', name: 'Antecedentes Criminais PB', type: 'PDF', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd4', name: 'Comprovante de Residência', type: 'PDF', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd5', name: 'Foto de Perfil Profissional', type: 'Imagem', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd6', name: 'Laudo Vistoria Veicular', type: 'PDF', status: 'aprovado', dateUploaded: 'Hoje' },
    ],
  },
  {
    id: 'app-3',
    userCode: 'W-0710',
    name: 'João Pedro Santos',
    type: 'passageiro',
    state: 'PB',
    city: 'João Pessoa',
    registerDate: 'Hoje, 08:47',
    docsSent: 3,
    docsTotal: 4,
    status: 'pendente',
    phone: '(83) 98899-5511',
    cpf: '071.***.***-15',
    documents: [
      { id: 'd1', name: 'Documento Oficial com Foto (RG)', type: 'Imagem', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd2', name: 'Comprovante de Endereço', type: 'PDF', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd3', name: 'Selfie de Confirmação Biometria', type: 'Imagem', status: 'pendente', dateUploaded: 'Hoje' },
    ],
  },
  {
    id: 'app-4',
    userCode: 'W-0711',
    name: 'Ana Beatriz Lima',
    type: 'passageiro',
    state: 'PB',
    city: 'João Pessoa',
    registerDate: 'Hoje, 08:21',
    docsSent: 4,
    docsTotal: 4,
    status: 'pendente',
    phone: '(83) 99155-2288',
    cpf: '055.***.***-90',
    documents: [
      { id: 'd1', name: 'Documento CNH', type: 'Imagem', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd2', name: 'Comprovante de Vínculo Trabalhista', type: 'PDF', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd3', name: 'Selfie com CNH', type: 'Imagem', status: 'aprovado', dateUploaded: 'Hoje' },
      { id: 'd4', name: 'Termo de Uso Assinado Digitalmente', type: 'PDF', status: 'aprovado', dateUploaded: 'Hoje' },
    ],
  },
  {
    id: 'app-5',
    userCode: 'W-0712',
    name: 'Fernanda Costa Mota',
    type: 'motorista',
    state: 'PB',
    city: 'João Pessoa',
    registerDate: 'Hoje, 07:58',
    docsSent: 2,
    docsTotal: 6,
    status: 'pendente',
    vehicleInfo: 'Yamaha Factor 150 - QFX-3011',
    category: 'W-MOTO COMUM',
    phone: '(83) 98777-6600',
    cpf: '062.***.***-34',
    documents: [
      { id: 'd1', name: 'CNH categoria A', type: 'Imagem', status: 'pendente', dateUploaded: 'Hoje' },
      { id: 'd2', name: 'CRLV', type: 'Imagem', status: 'pendente', dateUploaded: 'Hoje' },
    ],
  },
];

export const initialOccurrences: Occurrence[] = [
  {
    id: 'oc-1',
    type: 'Objeto esquecido',
    description: 'Bolsa preta com documentos e chaves no banco traseiro',
    date: 'Hoje 11:20',
    status: 'aberta',
    driver: 'Lucas Martins (Fiat Mobi)',
    passenger: 'Renata Meireles',
    rideId: '#894562',
    priority: 'alta',
  },
  {
    id: 'oc-2',
    type: 'Dano ao veículo',
    description: 'Mancha de café no estofado dianteiro durante corrida corporativa',
    date: 'Hoje 10:45',
    status: 'em_analise',
    driver: 'Carlos Eduardo (Onix)',
    passenger: 'Mateus Silveira',
    rideId: '#894561',
    priority: 'media',
  },
  {
    id: 'oc-3',
    type: 'Higienização',
    description: 'Vômito leve no tapete traseiro (solicitação de taxa higienização R$ 120)',
    date: 'Hoje 09:30',
    status: 'aberta',
    driver: 'Thiago Farias (Táxi)',
    passenger: 'André Queiroz',
    rideId: '#894560',
    priority: 'alta',
  },
  {
    id: 'oc-4',
    type: 'Objeto esquecido',
    description: 'Celular Samsung Galaxy S23 encontrado no veículo entregue na Central',
    date: 'Hoje 07:50',
    status: 'resolvida',
    driver: 'Diego Wallace',
    passenger: 'Bruna Diniz',
    rideId: '#894558',
    priority: 'baixa',
  },
];

export const initialRecentRides: Ride[] = [
  {
    id: '#894562',
    passengerName: 'Camila Rocha',
    driverName: 'Diego Wallace',
    driverVehicle: 'Honda CG 160',
    category: 'W-MOTO COMUM',
    origin: 'Manaíra (Av. Edson Ramalho)',
    destination: 'Centro (Parque Solon)',
    distanceKm: 5.4,
    durationMin: 14,
    price: 13.5,
    commissionRate: 0.1,
    commissionValue: 1.35,
    netDriverValue: 12.15,
    status: 'concluida',
    timestamp: 'Há 4 min',
    paymentMethod: 'Pix',
    rideType: 'avulsa',
    multiplierDynamic: 1.0,
    paymentStatus: 'confirmado',
    state: 'PB',
  },
  {
    id: '#894561',
    passengerName: 'Rodrigo Lima',
    driverName: 'Carlos Eduardo',
    driverVehicle: 'Chevrolet Onix',
    category: 'W-CARRO COMUM',
    origin: 'Bessa (Caribessa)',
    destination: 'Tambaú (Feirinha)',
    distanceKm: 6.8,
    durationMin: 18,
    price: 22.8,
    commissionRate: 0.1,
    commissionValue: 2.28,
    netDriverValue: 20.52,
    status: 'concluida',
    timestamp: 'Há 12 min',
    paymentMethod: 'Cartão',
    rideType: 'avulsa',
    multiplierDynamic: 1.0,
    paymentStatus: 'confirmado',
    state: 'PB',
  },
  {
    id: '#894560',
    passengerName: 'Valéria Santos',
    driverName: 'Roberto Cavalcanti',
    driverVehicle: 'Toyota Corolla',
    category: 'W-EXECUTIVO',
    origin: 'Aeroporto Castro Pinto',
    destination: 'Cabo Branco (Hotel Oceana)',
    distanceKm: 22.3,
    durationMin: 32,
    price: 94.0,
    commissionRate: 0.1,
    commissionValue: 9.4,
    netDriverValue: 84.6,
    status: 'concluida',
    timestamp: 'Há 25 min',
    paymentMethod: 'W-Bank',
    rideType: 'avulsa',
    multiplierDynamic: 1.0,
    paymentStatus: 'confirmado',
    state: 'PB',
  },
  {
    id: '#894559',
    passengerName: 'Felipe Dantas',
    driverName: 'Thiago Farias',
    driverVehicle: 'E-Bike Urbana',
    category: 'W-BIKE',
    origin: 'Tambaú (Busto Tamandaré)',
    destination: 'Manaíra (Praia)',
    distanceKm: 2.1,
    durationMin: 8,
    price: 7.0,
    commissionRate: 0.1,
    commissionValue: 0.7,
    netDriverValue: 6.3,
    status: 'concluida',
    timestamp: 'Há 38 min',
    paymentMethod: 'Pix',
    rideType: 'avulsa',
    multiplierDynamic: 1.0,
    paymentStatus: 'confirmado',
    state: 'PB',
  },
];

export const jpLocations = [
  { name: 'Manaíra Shopping', neighborhood: 'Manaíra', x: 260, y: 150, lat: -7.0985, lng: -34.8362 },
  { name: 'Praia do Bessa (Caribessa)', neighborhood: 'Bessa', x: 220, y: 80, lat: -7.0722, lng: -34.8458 },
  { name: 'Busto de Tamandaré / Feirinha', neighborhood: 'Tambaú', x: 310, y: 220, lat: -7.1145, lng: -34.8285 },
  { name: 'Orla de Cabo Branco', neighborhood: 'Cabo Branco', x: 335, y: 280, lat: -7.1298, lng: -34.8234 },
  { name: 'Farol do Cabo Branco / Ponta do Seixas', neighborhood: 'Altiplano', x: 360, y: 350, lat: -7.1472, lng: -34.7958 },
  { name: 'Parque Solon de Lucena (Lagoa)', neighborhood: 'Centro', x: 130, y: 260, lat: -7.1215, lng: -34.8821 },
  { name: 'Mangabeira Shopping', neighborhood: 'Mangabeira', x: 220, y: 370, lat: -7.1685, lng: -34.8542 },
  { name: 'Aeroporto Castro Pinto', neighborhood: 'Bayeux / JP', x: 50, y: 320, lat: -7.1469, lng: -34.9511 },
  { name: 'Clínicas Epitácio Pessoa', neighborhood: 'Torre', x: 200, y: 220, lat: -7.1158, lng: -34.8624 },
];

export const initialTransportContracts: TransportContract[] = [
  {
    id: 'ctr-1',
    contractNumber: 'W-CTR-2026-001',
    clientName: 'Ana Cláudia (Comércio Torre)',
    clientCode: 'W-0708',
    clientType: 'trabalhador_clt',
    period: 'mensal',
    category: 'W-MOTO COMUM',
    fixedRatePerKm: 1.0, // R$ 1,00/km fixo sem dinâmica
    dailyDistanceKm: 14.5,
    dailyValue: 14.5,
    totalPeriodValue: 319.0,
    hasSafePoint: false,
    originAddress: 'Bessa (Residencial Atlantis)',
    destinationAddress: 'Torre / Clínicas Epitácio',
    pickupTime: '09:00',
    returnTime: '18:15',
    status: 'ativo',
    prepaidStatus: 'pago',
    assignedDriverId: 'drv-1',
    assignedDriverName: 'Diego Wallace (W-0701)',
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    observations: 'Cliente pontual. Pagamento mensal antecipado via Pix. Tarifa 100% blindada contra dinâmica.',
  },
  {
    id: 'ctr-2',
    contractNumber: 'W-CTR-2026-002',
    clientName: 'Dr. Marcos Albuquerque',
    clientCode: 'W-0709',
    clientType: 'empresa',
    period: 'mensal',
    category: 'W-CARRO COMUM',
    fixedRatePerKm: 1.75, // R$ 1,75/km fixo sem dinâmica
    dailyDistanceKm: 12.0,
    dailyValue: 21.0,
    totalPeriodValue: 462.0,
    hasSafePoint: false,
    originAddress: 'Centro Médico Tambaú',
    destinationAddress: 'Manaíra Shopping (Praça Gourmet)',
    pickupTime: '12:15',
    returnTime: '14:00',
    status: 'ativo',
    prepaidStatus: 'pago',
    assignedDriverId: 'drv-2',
    assignedDriverName: 'Carlos Eduardo (W-0702)',
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    observations: 'Veículo com ar condicionado e som ambiente. Faturamento PJ mensal.',
  },
  {
    id: 'ctr-3',
    contractNumber: 'W-CTR-2026-003',
    clientName: 'Camila & Sofia (Escola Maple Bear)',
    clientCode: 'W-0710',
    clientType: 'estudante',
    period: 'mensal',
    category: 'W-CARRO PRIME',
    fixedRatePerKm: 2.0, // R$ 2,00/km fixo
    dailyDistanceKm: 18.0,
    dailyValue: 36.0,
    totalPeriodValue: 792.0,
    hasSafePoint: true,
    safePointDetails: 'Av. Pres. Epitácio Pessoa (em frente ao Hiper Pão de Açúcar) – Ponto Seguro W-DRIVER',
    originAddress: 'Altiplano Nobre (Residencial Tour Geneve)',
    destinationAddress: 'Escola Internacional Miramar',
    pickupTime: '12:30',
    returnTime: '17:45',
    status: 'ativo',
    prepaidStatus: 'pago',
    assignedDriverId: 'drv-7',
    assignedDriverName: 'José Augusto Ferreira (W-0707)',
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    observations: 'Ponto Seguro validado pela Central. Embarque e desembarque assistido com total discrição.',
  },
];

export const initialSafePoints: SafePoint[] = [
  {
    id: 'sp-1',
    neighborhood: 'Bairro São José / Manaíra',
    referenceAddress: 'Av. Gov. Flávio Ribeiro Coutinho (Em frente ao Manaíra Shopping)',
    safePointName: 'Ponto Seguro Norte 01 (Shopping)',
    justification: 'Via com grande fluxo, iluminação pública plena, câmeras de monitoramento e fácil acesso viário.',
    active: true,
    lat: -7.0985,
    lng: -34.8362,
  },
  {
    id: 'sp-2',
    neighborhood: 'Renascer / BR-230',
    referenceAddress: 'BR-230 km 14 (Posto Futurama - Conveniência 24h)',
    safePointName: 'Ponto Seguro Intermunicipal 02 (Posto BR)',
    justification: 'Ponto iluminado 24 horas, suporte de frentistas e estacionamento seguro para embarque discreto.',
    active: true,
    lat: -7.1080,
    lng: -34.8650,
  },
  {
    id: 'sp-3',
    neighborhood: 'Rangel / Cristo Redentor',
    referenceAddress: 'Av. 2 de Fevereiro (Em frente à Farmácia Central)',
    safePointName: 'Ponto Seguro Sul 03 (Comércio Central)',
    justification: 'Ponto estratégico em avenida principal com segurança comercial e parada rápida permitida.',
    active: true,
    lat: -7.1420,
    lng: -34.8720,
  },
  {
    id: 'sp-4',
    neighborhood: 'Roger / Centro Histórico',
    referenceAddress: 'Parque Solon de Lucena (Anel da Lagoa - Guarita da Guarda Municipal)',
    safePointName: 'Ponto Seguro Centro 04 (Lagoa / Guarda)',
    justification: 'Área com policiamento ostensivo, amplo espaço de parada e facilidade de escoamento de tráfego.',
    active: true,
    lat: -7.1215,
    lng: -34.8821,
  },
];

export const initialStates: StateOperation[] = [
  {
    uf: 'PB',
    name: 'Paraíba',
    capital: 'João Pessoa',
    status: 'liberado',
    activeDrivers: 7,
    activePassengers: 142,
    totalRides: 894,
    lastUpdated: 'Hoje às 07:30',
  },
  {
    uf: 'PE',
    name: 'Pernambuco',
    capital: 'Recife',
    status: 'bloqueado',
    activeDrivers: 0,
    activePassengers: 0,
    totalRides: 0,
    lastUpdated: 'Central: Em estudo de expansão',
  },
  {
    uf: 'RN',
    name: 'Rio Grande do Norte',
    capital: 'Natal',
    status: 'bloqueado',
    activeDrivers: 0,
    activePassengers: 0,
    totalRides: 0,
    lastUpdated: 'Central: Em estudo de expansão',
  },
  {
    uf: 'CE',
    name: 'Ceará',
    capital: 'Fortaleza',
    status: 'bloqueado',
    activeDrivers: 0,
    activePassengers: 0,
    totalRides: 0,
    lastUpdated: 'Central: Em estudo de expansão',
  },
  {
    uf: 'SP',
    name: 'São Paulo',
    capital: 'São Paulo',
    status: 'bloqueado',
    activeDrivers: 0,
    activePassengers: 0,
    totalRides: 0,
    lastUpdated: 'Central: Bloqueado',
  },
  {
    uf: 'RJ',
    name: 'Rio de Janeiro',
    capital: 'Rio de Janeiro',
    status: 'bloqueado',
    activeDrivers: 0,
    activePassengers: 0,
    totalRides: 0,
    lastUpdated: 'Central: Bloqueado',
  },
  {
    uf: 'BA',
    name: 'Bahia',
    capital: 'Salvador',
    status: 'bloqueado',
    activeDrivers: 0,
    activePassengers: 0,
    totalRides: 0,
    lastUpdated: 'Central: Bloqueado',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    adminName: 'Diego Wallace (Central)',
    action: 'Definição de Tarifa Base',
    category: 'tarifas',
    fieldModified: 'W-MOTO COMUM: Taxa Fixa até 4km',
    previousValue: 'R$ 5,50',
    newValue: 'R$ 6,00 (Acima de 4km: R$ 1,00/km total)',
    timestamp: '13/09/2026 06:15',
  },
  {
    id: 'log-2',
    adminName: 'Diego Wallace (Central)',
    action: 'Validação de Ponto Seguro',
    category: 'segurança',
    fieldModified: 'Ponto Seguro Norte 01 – Av. Flávio Ribeiro Coutinho',
    previousValue: 'Pendente',
    newValue: 'Ativo e Homologado',
    timestamp: '13/09/2026 06:30',
  },
  {
    id: 'log-3',
    adminName: 'Diego Wallace (Central)',
    action: 'Bloqueio Geográfico de Expansão',
    category: 'estados',
    fieldModified: 'Status de Operação Nacional',
    previousValue: 'Todos Bloqueados',
    newValue: 'Apenas PB Habilitada (Outros 26 estados Bloqueados)',
    timestamp: '13/09/2026 07:00',
  },
];

export const initialThirdParties: ThirdPartyPassenger[] = [
  {
    id: 'tp-1',
    name: 'João Silva Neto (Familiar)',
    cpf: '098.765.432-11',
    phone: '(83) 98700-1122',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    rating: 5.0,
    totalRides: 14,
    addressProof: 'Comprovante Residencial Manaíra - PB anexado',
  },
  {
    id: 'tp-2',
    name: 'Dra. Maria Clara Barbosa (Colaboradora)',
    cpf: '444.555.666-77',
    phone: '(83) 99123-4567',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    rating: 4.95,
    totalRides: 8,
    addressProof: 'Comprovante Clínica Tambaú - PB anexado',
  },
  {
    id: 'tp-3',
    name: 'Lucas Gabriel Cavalcanti (Estudante)',
    cpf: '777.888.999-00',
    phone: '(83) 99888-3344',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    totalRides: 5,
    addressProof: 'Comprovante Residencial Bessa - PB anexado',
  },
];

export const initialMediaRecords: RideMediaRecord[] = [
  {
    id: 'med-001',
    rideId: '#894563',
    type: 'audio',
    filename: 'rec_audio_ride_894563.m4a',
    durationSec: 840,
    recordedAt: '13/09/2026 10:45',
    startedAt: '10:45:10',
    endedAt: '10:59:10',
    driverCode: 'W-0701',
    passengerCode: 'W-PASS-0705',
    status: 'gravado',
    sizeMb: 6.4,
    storagePath: '/wdriver-secure-vault/rides/894563/audio_encrypted.m4a',
  },
  {
    id: 'med-002',
    rideId: '#894563',
    type: 'video',
    filename: 'rec_video_dash_894563.mp4',
    durationSec: 840,
    recordedAt: '13/09/2026 10:45',
    startedAt: '10:45:10',
    endedAt: '10:59:10',
    driverCode: 'W-0701',
    passengerCode: 'W-PASS-0705',
    status: 'gravado',
    sizeMb: 48.2,
    storagePath: '/wdriver-secure-vault/rides/894563/video_dash_encrypted.mp4',
  },
  {
    id: 'med-003',
    rideId: '#894512',
    type: 'audio',
    filename: 'rec_audio_ride_894512.m4a',
    durationSec: 620,
    recordedAt: '13/09/2026 09:15',
    startedAt: '09:15:00',
    endedAt: '09:25:20',
    driverCode: 'W-0702',
    passengerCode: 'W-PASS-0705',
    status: 'arquivado',
    sizeMb: 4.8,
    storagePath: '/wdriver-secure-vault/archive/rides/894512/audio.m4a',
  },
];

export const initialBlockedPairs: BlockedUserPair[] = [
  {
    id: 'blk-001',
    blockerCode: 'W-0703',
    blockerName: 'Lucas Martins Oliveira (Motorista)',
    blockedCode: 'W-PASS-9901',
    blockedName: 'Passageiro Exemplo Bloqueado',
    reason: 'Incompatibilidade operacional reportada com solicitação mútua de não pareamento',
    date: '10/09/2026',
    active: true,
  },
];

export const initialDemoUsers: AppUser[] = [
  {
    id: 'usr-admin-1',
    userCode: 'W-ADM-001',
    name: 'Diego Wallace (CEO & Central)',
    email: 'admin@wdriver.com.br',
    role: 'admin',
    phone: '(83) 98841-0001',
    cpf: '012.345.678-90',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    state: 'PB',
    city: 'João Pessoa',
    status: 'ativo',
  },
  {
    id: 'usr-driver-w0701',
    userCode: 'W-0701',
    name: 'Diego Wallace (Proprietário Autorizado W-0701)',
    email: 'diego.proprietario@wdriver.com.br',
    role: 'motorista',
    phone: '(83) 98841-2099',
    cpf: '012.345.678-90',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    state: 'PB',
    city: 'João Pessoa',
    status: 'ativo',
    isOwnerAdmin: true,
    category: 'W-MOTO COMUM',
    activeCategory: 'W-MOTO COMUM',
    enabledCategories: [
      'W-BIKE',
      'W-MOTO COMUM',
      'W-MOTO PRIME',
      'W-CARRO COMUM',
      'W-CARRO PRIME',
      'W-EXECUTIVO',
      'W-TÁXI',
      'W-LUXO',
    ],
    vehicle: 'Honda CG 160 Titan',
    plate: 'QFA-8921',
    rating: 5.0,
    completedRides: 24,
    todayEarnings: 380.0,
  },
  {
    id: 'usr-driver-1',
    userCode: 'W-0702',
    name: 'Carlos Eduardo Silva',
    email: 'carlos.motorista@wdriver.com.br',
    role: 'motorista',
    phone: '(83) 98712-4433',
    cpf: '123.456.789-00',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    state: 'PB',
    city: 'João Pessoa',
    status: 'ativo',
    vehicle: 'Chevrolet Onix Plus',
    plate: 'QFL-4412',
    category: 'W-CARRO COMUM',
    rating: 4.95,
    completedRides: 18,
    todayEarnings: 215.4,
  },
  {
    id: 'usr-pass-1',
    userCode: 'W-PASS-0705',
    name: 'Ana Cláudia Mendes',
    email: 'ana.claudia@gmail.com',
    role: 'passageiro',
    phone: '(83) 98822-1011',
    cpf: '345.678.901-22',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    state: 'PB',
    city: 'João Pessoa',
    status: 'ativo',
    activeContractId: 'W-CTR-2026-001',
    savedPointsCount: 4,
  },
];

export const initialOfficialInterdictions: OfficialRoadInterdiction[] = [
  {
    id: 'int-01',
    roadName: 'Av. Cabo Branco (Trecho Barreira do Cabo Branco)',
    neighborhood: 'Cabo Branco',
    centerLat: -7.1475,
    centerLng: -34.7990,
    radiusMeters: 350,
    reason: 'Interdição oficial: obras de contenção e drenagem da falésia / risco geológico.',
    registeredBy: 'Defesa Civil / SEMOB / Central W-DRIVER',
    active: true,
    detourWaypointLat: -7.1410,
    detourWaypointLng: -34.8150, // Contorno seguro por Altiplano
    dateStart: '2026-03-01',
  },
  {
    id: 'int-02',
    roadName: 'Rua Maciel Pinheiro (Varadouro / Centro Histórico)',
    neighborhood: 'Varadouro',
    centerLat: -7.1180,
    centerLng: -34.8870,
    radiusMeters: 250,
    reason: 'Interdição oficial: restauração de calçamento histórico e fiação subterrânea.',
    registeredBy: 'SEINFRA / SEMOB João Pessoa',
    active: true,
    detourWaypointLat: -7.1235,
    detourWaypointLng: -34.8820, // Contorno por Av. Sanhauá
    dateStart: '2026-03-10',
  },
];

// Cálculo de distância Haversine em metros entre duas coordenadas
export function getDistanceMeters(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371e3; // Metros
  const phi1 = (lat1 * Math.PI) / 180;
  const phi2 = (lat2 * Math.PI) / 180;
  const deltaPhi = ((lat2 - lat1) * Math.PI) / 180;
  const deltaLambda = ((lon2 - lon1) * Math.PI) / 180;

  const a =
    Math.sin(deltaPhi / 2) * Math.sin(deltaPhi / 2) +
    Math.cos(phi1) * Math.cos(phi2) * Math.sin(deltaLambda / 2) * Math.sin(deltaLambda / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

// Verifica se uma polilinha cruza algum trecho interditado oficialmente
export function findInterdictionCrossing(
  polyline: [number, number][],
  interdictions: OfficialRoadInterdiction[]
): OfficialRoadInterdiction | null {
  const activeInterdictions = interdictions.filter((i) => i.active);
  for (const point of polyline) {
    const [pLat, pLng] = point;
    for (const inter of activeInterdictions) {
      const dist = getDistanceMeters(pLat, pLng, inter.centerLat, inter.centerLng);
      if (dist <= inter.radiusMeters) {
        return inter;
      }
    }
  }
  return null;
}
